# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

# This creates the proxy for production
[[redirects]]
  from = "/api/hf/*"
  to = "https://api-inference.huggingface.co/:splat"
  status = 200
  force = true